### ISSUE TITLE
三个页面嵌套@@include时，怎么调用带的参数呢？

### ISSUE THREAD

**Issue by xcheukx** [iwares/gulp-art-include#1]
a.html
@@include('b.html',{"name":"aaa"})

b.html
@@include('c.html',{"name":{{name}}}) //这里该怎么调用呢，直接写{{name}}的话，会报错，写name就不符合规范，只能填写字符串的形式吗？

**Comment by ericlogic** [comment]
<code>@@include('c.html',{"name":"{{name}}"})</code>，在<code>{{name}}</code>外层加上<code>""</code>就可以了。

归纳一下：
简单的值，可以通过以下方式实现。注意：由于是字符串，{{content}}在作为参数网下层传递时需要加""。

```
<!-- p.html -->
<p>{{content}}</p>
```

```
<!-- section.html -->
<section>
<h1>{{title}}</h1>
@@include("p.html", {
	"content" : "{{content}}"
	})
</section>
```

```
<!-- main.html -->
<article>
@@include("section.html" : {
	"title" : "This is title",
	"content" : "I'm content"
})
</article>
```

复杂的json对象传递，可以通过artTemplate的helper来实现。
